
export const COMMON_FUNCTIONS = [
  "SUM", "AVERAGE", "COUNT", "MAX", "MIN", "IF", "VLOOKUP", "HLOOKUP", "INDEX", "MATCH",
  "CONCATENATE", "LEFT", "RIGHT", "MID", "LEN", "TRIM", "UPPER", "LOWER", "PROPER",
  "TODAY", "NOW", "DATE", "YEAR", "MONTH", "DAY", "ROUND", "ROUNDUP", "ROUNDDOWN",
  "ABS", "SQRT", "POWER", "MOD", "RAND", "RANDBETWEEN", "SUMIF", "COUNTIF", "AVERAGEIF",
  "IFERROR", "AND", "OR", "NOT", "TRUE", "FALSE", "XLOOKUP", "UNIQUE", "SORT", "FILTER"
].sort();
